// <auto-generated />
using System;
using ApiClassicGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiClassicGames.Migrations
{
    [DbContext(typeof(DbGamesContext))]
    [Migration("20240913123138_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiClassicGames.Models.ClassicGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desenvolvedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publicador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassicGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 1991,
                            Categoria = "Luta",
                            Descricao = "This is Street Fighter",
                            Desenvolvedor = "CAPCOM",
                            Foto = "https://game.capcom.com/manual/CFC/locale/page/101_3_1.jpg?t=202209261200",
                            Nome = "Street Fighter II",
                            Plataforma = "Arcade",
                            Publicador = "CAPCOM",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 1992,
                            Categoria = "Luta",
                            Descricao = "Fight for your life",
                            Desenvolvedor = "Midway",
                            Foto = "https://s2-techtudo.glbimg.com/GkH4Ha_ebZMOzoDnBJqUIwfuVnE=/0x0:695x442/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/V/T/tTvJnBQYeobx3NwcwESQ/2015-06-29-mortalkombat-1992.jpg",
                            Nome = "Mortal Kombat",
                            Plataforma = "Arcade",
                            Publicador = "Warner",
                            Status = "Ativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
